### PR TITLE
[WIP] Address Gabe's feedback

### LINKED ISSUE #4: Review feedback
Had a chance to review! Some feedback:

- Msg's without the brackets do not compile with [ts-codegen](https://github.com/CosmWasm/ts-codegen)
```diff
enum QueryMsg {
 	#[returns(VaultInfo)]
- 	Info
+ 	Info {}
}
```
- I like the idea of custom callback, but do you have any examples of this in use?
- I see `receiver: Option<String>` frequently used. Is this a common need? or a standard contract api field? Does `None` imply that the actions will be executed for the sender?
- For `QueryMsg::PreviewRedeem`, I'd rename the field `shares` to just `amount`.
- Instead of using the term `Assets`, can we just call it `Coins`?
- We need a query message like: `TotalVaultCoinsIssued {}` in order to price Vault tokens. Here's an example: https://github.com/mars-protocol/rover/blob/d2bd15ff54a59b1cc97bf14ad4a57975bdec98cc/contracts/mars-oracle-adapter/src/contract.rs#L131 of it in use.
- If we renamed `deposit_coins` to `entry_reqs` is that clearer?
- For `LockupQueryMsg::Lockup` and `ForceWithdrawUnlocking`, the field `owner` is required. Why would that be needed? Lockup Ids are unique no?
- Can you update cw-utils to 0.16?
- I find the automated action by leaving lockup_id as `None` to be too smart:
```diff
    WithdrawUnlocked {
         receiver: Option<String>,
-        lockup_id: Option<u64>,
+        lockup_id: u64,
    },
```
- `ForceWithdrawUnlocking` takes `amounts: Option<Vec<Coin>>`. How does the owner know the underlying coins in the lockup in order to do a partial liquidation? No current query supports this. It seems that the Lockup struct needs a `coins: Vec<Coin>` field instead of `amount`.
- Not really clear for me what the use cases for these are
  - PreviewWithdraw
  - PreviewMint
  - MaxDeposit
  - MaxMint
  - MaxWithdraw
  - MaxRedeem
  - ConvertToShares (how is this different than PreviewDeposit?)
  - ConvertToAssets (how is this different than PreviewRedeem?)
- Can you export the event strings? I had something like this:
```rust
pub const UNLOCKING_POSITION_CREATED_EVENT_TYPE: &str = "unlocking_position_created";
pub const UNLOCKING_POSITION_ATTR: &str = "id";
```
- In VaultStandardInfo, can pub extensions: Vec<String>, be more strongly typed? Maybe instead of String an enum?
- What happens when you query LockupDuration on a vault that doesn't have one? It raises an exception?

### PR DESCRIPTION
**Pull request by apollo-pacman**
closes #4 

## Tasks
- [x] Msg's without the brackets do not compile with [ts-codegen](https://github.com/CosmWasm/ts-codegen)
```diff
enum QueryMsg {
 	#[returns(VaultInfo)]
- 	Info
+ 	Info {}
}
```
- [x] I like the idea of custom callback, but do you have any examples of this in use?
- [x] I see `receiver: Option<String>` frequently used. Is this a common need? or a standard contract api field? Does `None` imply that the actions will be executed for the sender?
- [x] For `QueryMsg::PreviewRedeem`, I'd rename the field `shares` to just `amount`.
- [ ] Instead of using the term `Assets`, can we just call it `Coins`?
- [x] We need a query message like: `TotalVaultCoinsIssued {}` in order to price Vault tokens. Here's an example: https://github.com/mars-protocol/rover/blob/d2bd15ff54a59b1cc97bf14ad4a57975bdec98cc/contracts/mars-oracle-adapter/src/contract.rs#L131 of it in use.
- [x] If we renamed `deposit_coins` to `entry_reqs` is that clearer?
- [x] For `LockupQueryMsg::Lockup` and `ForceWithdrawUnlocking`, the field `owner` is required. Why would that be needed? Lockup Ids are unique no?
- [x] Can you update cw-utils to 0.16?
- [x] I find the automated action by leaving lockup_id as `None` to be too smart:
```diff
    WithdrawUnlocked {
         receiver: Option<String>,
-        lockup_id: Option<u64>,
+        lockup_id: u64,
    },
```
- [x] `ForceWithdrawUnlocking` takes `amounts: Option<Vec<Coin>>`. How does the owner know the underlying coins in the lockup in order to do a partial liquidation? No current query supports this. It seems that the Lockup struct needs a `coins: Vec<Coin>` field instead of `amount`.
- [x] Not really clear for me what the use cases for these are
  - PreviewWithdraw
  - PreviewMint
  - MaxDeposit
  - MaxMint
  - MaxWithdraw
  - MaxRedeem
  - ConvertToShares (how is this different than PreviewDeposit?)
  - ConvertToAssets (how is this different than PreviewRedeem?)
- [x] Can you export the event strings? I had something like this:
```rust
pub const UNLOCKING_POSITION_CREATED_EVENT_TYPE: &str = "unlocking_position_created";
pub const UNLOCKING_POSITION_ATTR: &str = "id";
```
- [x] In VaultStandardInfo, can pub extensions: Vec<String>, be more strongly typed? Maybe instead of String an enum?
- [x] What happens when you query LockupDuration on a vault that doesn't have one? It raises an exception?

### CODE REVIEW

**Comment by apollo-pacman** [comment]
>  I like the idea of custom callback, but do you have any examples of this in use?
I removed Callback.  We will implement it as an extension instead

**Comment by apollo-pacman** [comment]
> What happens when you query LockupDuration on a vault that doesn't have one? It raises an exception?

Such a vault would not implement the Lockup extension. So it would fail to deserialize the message into a valid variant

**Comment by apollo-pacman** [comment]
> In VaultStandardInfo, can pub extensions: Vec, be more strongly typed? Maybe instead of String an enum?

We can't because if we do then others cannot implement their own extensions without creating a PR to the to the standard repo to update that enum

File: src/extensions/lockup.rs [hunk 1]
```diff
@@ -91,5 +98,7 @@ pub struct Lockup {
     pub owner: Addr,
     pub id: u64,
     pub release_at: Expiration,
-    pub amount: Uint128,
+    pub coins: Vec<Coin>,
+    #[cfg(feature = "cw20")]
+    pub cw20s: Vec<Cw20Coin>,
```
Comment (apollo-pacman) [inline src/extensions/lockup.rs:103]: > ForceWithdrawUnlocking takes amounts: Option<Vec<Coin>>. How does the owner know the underlying coins in the lockup in order to do a partial liquidation? No current query supports this. It seems that the Lockup struct needs a coins: Vec<Coin> field instead of amount.

@apollo-sturdy is this the way to do this? Avoids introducing a `cw_asset` dependency.

**Comment by apollo-pacman** [comment]
> ForceWithdrawUnlocking takes amounts: Option<Vec<Coin>>. How does the owner know the underlying coins in the lockup in order to do a partial liquidation? No current query supports this. It seems that the Lockup struct needs a coins: Vec<Coin> field instead of amount.

Since the unlocking positions on osmosis are denominated in LP tokens I think the `Lockup` struct should remain as is but the `ForceWithdrawUnlocking` message should take an `amount: Option<Uint128>` instead. We can't really denominate the unlocking positions in something other than LPs since the underlying liquidity in the pool changes all the time

File: src/extensions/lockup.rs [hunk 2]
```diff
@@ -21,21 +28,23 @@ pub enum LockupExecuteMsg {
...
     WithdrawUnlocked {
         /// An optional field containing which address should receive the
-        /// withdrawn underlying assets.
+        /// withdrawn underlying assets. If not set, the caller address will be
+        /// used instead.
         recipient: Option<String>,
         /// The ID of the expired lockup to withdraw from.
         /// If None is passed, the vault will attempt to withdraw all expired
         /// lockup positions. Note that this can fail if there are too many
         /// lockup positions and the `max_contract_gas` limit is hit.
```
Comment (apollo-sturdy) [inline src/extensions/lockup.rs:37]: Remove comment now that its no longer and Option.

File: src/extensions/lockup.rs [hunk 3]
```diff
@@ -44,15 +53,13 @@ pub enum LockupExecuteMsg {
...
     /// already been called).
     ForceWithdrawUnlocking {
-        /// The address of the owner of the position.
-        owner: String,
         /// The ID of the unlocking position from which to force withdraw
         lockup_id: u64,
         /// Optional amounts of each underlying asset to be force withdrawn.
         /// If None is passed, the entire position will be force withdrawn.
         /// Vaults MAY require the ratio of assets to be the same as the ratio
         /// in the `deposit_assets` field returned by the `VaultInfo` query.
```
Comment (apollo-sturdy) [inline src/extensions/lockup.rs:61]: Comment outdated.

**Review by apollo-sturdy — APPROVED** [review]

**Comment by apollo-sturdy** [comment]
Merged but left three items undone. Will be done in https://github.com/apollodao/cosmos-vault-standard/issues/11
